apiVersion: keti.migration/v1
kind: StatefulSet
metadata:
  name: statefulsettest
spec:
  serviceName: "ticker"
  replicas: 3
  selector:
    matchLabels:
      app: ticker
  template:
    metadata:
      labels:
        app: ticker
    spec:
      containers:
      - name: nginx
        image: hth0919/ticker:v0.0.4
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      selector:
        matchLabels:
          name: www
