apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: replicasets.keti.migration
spec:
  group: keti.migration
  names:
    kind: ReplicaSet
    listKind: ReplicaSetList
    plural: replicasets
    singular: replicaset
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: ReplicaSet ensures that a specified number of pod replicas are
        running at any given time.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'If the Labels of a ReplicaSet are empty, they are defaulted
            to be the same as the Pod(s) that the ReplicaSet manages. Standard object''s
            metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata'
          type: object
        spec:
          description: 'Spec defines the specification of the desired behavior of
            the ReplicaSet. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          properties:
            minReadySeconds:
              description: Minimum number of seconds for which a newly created pod
                should be ready without any of its container crashing, for it to be
                considered available. Defaults to 0 (pod will be considered available
                as soon as it is ready)
              format: int32
              type: integer
            replicas:
              description: 'Replicas is the number of desired replicas. This is a
                pointer to distinguish between explicit zero and unspecified. Defaults
                to 1. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller'
              format: int32
              type: integer
            selector:
              description: 'Selector is a label query over pods that should match
                the replica count. Label keys and values that must match in order
                to be controlled by this replica set. It must match the pod template''s
                labels. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors'
              properties:
                matchExpressions:
                  description: matchExpressions is a list of label selector requirements.
                    The requirements are ANDed.
                  items:
                    description: A label selector requirement is a selector that contains
                      values, a key, and an operator that relates the key and values.
                    properties:
                      key:
                        description: key is the label key that the selector applies
                          to.
                        type: string
                      operator:
                        description: operator represents a key's relationship to a
                          set of values. Valid operators are In, NotIn, Exists and
                          DoesNotExist.
                        type: string
                      values:
                        description: values is an array of string values. If the operator
                          is In or NotIn, the values array must be non-empty. If the
                          operator is Exists or DoesNotExist, the values array must
                          be empty. This array is replaced during a strategic merge
                          patch.
                        items:
                          type: string
                        type: array
                    required:
                    - key
                    - operator
                    type: object
                  type: array
                matchLabels:
                  additionalProperties:
                    type: string
                  description: matchLabels is a map of {key,value} pairs. A single
                    {key,value} in the matchLabels map is equivalent to an element
                    of matchExpressions, whose key field is "key", the operator is
                    "In", and the values array contains only "value". The requirements
                    are ANDed.
                  type: object
              type: object
            template:
              #$ref: '#/definitions/k8s.io~1api~1core~1v1~0PodTemplateSpec'
              description: 'Template is the object that describes the pod that will
                be created if insufficient replicas are detected. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller#pod-template'
          required:
          - selector
          type: object
        status:
          description: 'Status is the most recently observed status of the ReplicaSet.
            This data may be out of date by some window of time. Populated by the
            system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          properties:
            availableReplicas:
              description: The number of available replicas (ready for at least minReadySeconds)
                for this replica set.
              format: int32
              type: integer
            conditions:
              description: Represents the latest available observations of a replica
                set's current state.
              items:
                description: ReplicaSetCondition describes the state of a replica
                  set at a certain point.
                properties:
                  lastTransitionTime:
                    description: The last time the condition transitioned from one
                      status to another.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of replica set condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            fullyLabeledReplicas:
              description: The number of pods that have labels matching the labels
                of the pod template of the replicaset.
              format: int32
              type: integer
            observedGeneration:
              description: ObservedGeneration reflects the generation of the most
                recently observed ReplicaSet.
              format: int64
              type: integer
            readyReplicas:
              description: The number of ready replicas for this replica set.
              format: int32
              type: integer
            replicas:
              description: 'Replicas is the most recently oberved number of replicas.
                More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller'
              format: int32
              type: integer
          required:
          - replicas
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
