apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployments.keti.migration
spec:
  group: keti.migration
  names:
    kind: Deployment
    listKind: DeploymentList
    plural: deployments
    singular: deployment
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Deployment enables declarative updates for Pods and ReplicaSets.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          #description: Standard object metadata.
          type: object
        spec:
          description: Specification of the desired behavior of the Deployment.
          properties:
            minReadySeconds:
              description: Minimum number of seconds for which a newly created pod
                should be ready without any of its container crashing, for it to be
                considered available. Defaults to 0 (pod will be considered available
                as soon as it is ready)
              format: int32
              type: integer
            paused:
              description: Indicates that the deployment is paused.
              type: boolean
            progressDeadlineSeconds:
              description: The maximum time in seconds for a deployment to make progress
                before it is considered to be failed. The deployment controller will
                continue to process failed deployments and a condition with a ProgressDeadlineExceeded
                reason will be surfaced in the deployment status. Note that progress
                will not be estimated during the time a deployment is paused. Defaults
                to 600s.
              format: int32
              type: integer
            replicas:
              description: Number of desired pods. This is a pointer to distinguish
                between explicit zero and not specified. Defaults to 1.
              format: int32
              type: integer
            revisionHistoryLimit:
              description: The number of old ReplicaSets to retain to allow rollback.
                This is a pointer to distinguish between explicit zero and not specified.
                Defaults to 10.
              format: int32
              type: integer
            selector:
              description: Label selector for pods. Existing ReplicaSets whose pods
                are selected by this will be the ones affected by this deployment.
                It must match the pod template's labels.
              properties:
                matchExpressions:
                  description: matchExpressions is a list of label selector requirements.
                    The requirements are ANDed.
                  items:
                    description: A label selector requirement is a selector that contains
                      values, a key, and an operator that relates the key and values.
                    properties:
                      key:
                        description: key is the label key that the selector applies
                          to.
                        type: string
                      operator:
                        description: operator represents a key's relationship to a
                          set of values. Valid operators are In, NotIn, Exists and
                          DoesNotExist.
                        type: string
                      values:
                        description: values is an array of string values. If the operator
                          is In or NotIn, the values array must be non-empty. If the
                          operator is Exists or DoesNotExist, the values array must
                          be empty. This array is replaced during a strategic merge
                          patch.
                        items:
                          type: string
                        type: array
                    required:
                    - key
                    - operator
                    type: object
                  type: array
                matchLabels:
                  additionalProperties:
                    type: string
                  description: matchLabels is a map of {key,value} pairs. A single
                    {key,value} in the matchLabels map is equivalent to an element
                    of matchExpressions, whose key field is "key", the operator is
                    "In", and the values array contains only "value". The requirements
                    are ANDed.
                  type: object
              type: object
            strategy:
              description: The deployment strategy to use to replace existing pods
                with new ones.
              properties:
                rollingUpdate:
                  description: 'Rolling update config params. Present only if DeploymentStrategyType
                    = RollingUpdate. --- TODO: Update this to follow our convention
                    for oneOf, whatever we decide it to be.'
                  properties:
                    maxSurge:
                      anyOf:
                      - type: integer
                      - type: string
                      description: 'The maximum number of pods that can be scheduled
                        above the desired number of pods. Value can be an absolute
                        number (ex: 5) or a percentage of desired pods (ex: 10%).
                        This can not be 0 if MaxUnavailable is 0. Absolute number
                        is calculated from percentage by rounding up. Defaults to
                        25%. Example: when this is set to 30%, the new ReplicaSet
                        can be scaled up immediately when the rolling update starts,
                        such that the total number of old and new pods do not exceed
                        130% of desired pods. Once old pods have been killed, new
                        ReplicaSet can be scaled up further, ensuring that total number
                        of pods running at any time during the update is at most 130%
                        of desired pods.'
                      x-kubernetes-int-or-string: true
                    maxUnavailable:
                      anyOf:
                      - type: integer
                      - type: string
                      description: 'The maximum number of pods that can be unavailable
                        during the update. Value can be an absolute number (ex: 5)
                        or a percentage of desired pods (ex: 10%). Absolute number
                        is calculated from percentage by rounding down. This can not
                        be 0 if MaxSurge is 0. Defaults to 25%. Example: when this
                        is set to 30%, the old ReplicaSet can be scaled down to 70%
                        of desired pods immediately when the rolling update starts.
                        Once new pods are ready, old ReplicaSet can be scaled down
                        further, followed by scaling up the new ReplicaSet, ensuring
                        that the total number of pods available at all times during
                        the update is at least 70% of desired pods.'
                      x-kubernetes-int-or-string: true
                  type: object
                type:
                  description: Type of deployment. Can be "Recreate" or "RollingUpdate".
                    Default is RollingUpdate.
                  type: string
              type: object
              #template:
                    #$ref: '#/definitions/k8s.io~1api~1core~1v1~0PodTemplateSpec'
                    # description: Template describes the pods that will be created.
          required:
          - selector
          - template
          type: object
        status:
          description: Most recently observed status of the Deployment.
          properties:
            availableReplicas:
              description: Total number of available pods (ready for at least minReadySeconds)
                targeted by this deployment.
              format: int32
              type: integer
            collisionCount:
              description: Count of hash collisions for the Deployment. The Deployment
                controller uses this field as a collision avoidance mechanism when
                it needs to create the name for the newest ReplicaSet.
              format: int32
              type: integer
            conditions:
              description: Represents the latest available observations of a deployment's
                current state.
              items:
                description: DeploymentCondition describes the state of a deployment
                  at a certain point.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of deployment condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            observedGeneration:
              description: The generation observed by the deployment controller.
              format: int64
              type: integer
            readyReplicas:
              description: Total number of ready pods targeted by this deployment.
              format: int32
              type: integer
            replicas:
              description: Total number of non-terminated pods targeted by this deployment
                (their labels match the selector).
              format: int32
              type: integer
            unavailableReplicas:
              description: Total number of unavailable pods targeted by this deployment.
                This is the total number of pods that are still required for the deployment
                to have 100% available capacity. They may either be pods that are
                running but not yet available or pods that still have not been created.
              format: int32
              type: integer
            updatedReplicas:
              description: Total number of non-terminated pods targeted by this deployment
                that have the desired template spec.
              format: int32
              type: integer
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
